name: Building Code V1

on: workflow_dispatch

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file
        run: |
          echo Moving Code File genedted by AI Sanbox
          cp ./samples_files/Program.txt ./Program.cs
        

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Adjust the .NET version as needed

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

     # - name: Run tests
     #   run: dotnet test --no-restore --verbosity normal
