name: Building Code V3

on: workflow_dispatch

env:
  IMAGE_NAME: sample-code
  TAG: ${{ github.sha }}
  #tag: latest
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy file
      run: |
        echo Moving Code File genedted by AI Sanbox
        cp ./samples_files/Program.txt ./Program.cs
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}/${{ env.ACR_NAME }}.azurecr.io:${{ env.TAG }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Push to ACR
      run: |
        docker push ${{ env.IMAGE_NAME }}/${{ env.ACR_NAME }}.azurecr.io:${{ env.TAG }}

    - name: Deploy to Azure Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.AZURE_RG }}
        name: ${{ secrets.AZURE_ACI_NAME }}
        image: ${{ env.IMAGE_NAME }}/${{ env.ACR_NAME }}.azurecr.io:${{ env.TAG }}
        registry-login-server: ${{ env.ACR_NAME }}.azurecr.io
        registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        dns-name-label: oa-test-001
        ports: 80
