name: Building Code V2

on: workflow_dispatch

env:
  #ACR_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  IMAGE_NAME: sample-code
  TAG: ${{ github.sha }}
  #tag: latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}
