name: Build Bouncy Castle Code Sample

on: workflow_dispatch

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file
        run: |
          echo Moving Code File genedted by AI Sanbox
          cp ./samples_files/Program.txt ./Program.cs
        

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Adjust the .NET version as needed

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

     # - name: Run tests
     #   run: dotnet test --no-restore --verbosity normal
  unit-test:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build
    steps:
      - name: Init Test
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Init Test Running'

  qa-environment:
    if: ${{ success() }}
    needs: [unit-test]
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: 'https://delightful-flower-012038310.1.azurestaticapps.net'  
    steps:
      - name: Deploy QA Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy QA Env'

  clean-repo:
    if: ${{ success() }}
    needs: qa-environment
    runs-on: ubuntu-latest  
    steps:
      - name: Clear
         git rm -f Program.cs
         git commit -m "AI Sandbox delete Program.txt file from repository."
         git push
